import type { ArxivSearchResult } from "@/lib/explore";

/** A text segment in an interleaved agent response. */
export interface TextSegmentBlock {
  type: "text_segment";
  content: string;
}

/** A tool invocation recorded in a chat message. */
export interface ToolCallBlock {
  type: "tool_call";
  id: string;
  name: string;
  input: Record<string, unknown>;
  output?: string;
}

/**
 * Structured content rendered in an assistant message.
 * For agentic responses, blocks are stored in display order (text_segment
 * interleaved with tool_call) so the interleaved view survives page reload.
 */
export type ChatAssistantBlock =
  | TextSegmentBlock
  | ToolCallBlock
  | { type: "learning_embed"; reviewId: string }
  | { type: "arxiv_hits"; query: string; results: ArxivSearchResult[] };

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: string;
  /** Rich panels for learning / literature actions (assistant only). */
  blocks?: ChatAssistantBlock[];
}

/** Structured summary of what the researcher learned from a paper. */
export interface PaperSummary {
  /** One-sentence takeaway. */
  takeaway: string;
  /** Key method or approach used. */
  method: string;
  /** Main result or finding. */
  result: string;
  /** Personal notes / reflections. */
  notes: string;
}

/** A saved paper review session: PDF + replayable Q&A. */
export interface PaperReview {
  id: string;
  title: string;
  /** arXiv paper ID. Null for locally-uploaded PDFs. */
  arxivId: string | null;
  createdAt: string;
  updatedAt: string;
  /** Absolute filesystem path for local PDFs. Null for arXiv papers. */
  pdfPath: string | null;
  /** Structured summary written by user or generated by AI. */
  summary: PaperSummary | null;
}
